server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $gateway_backend http://api-gateway.default.svc.cluster.local:8080;
        proxy_pass $gateway_backend;
        proxy_set_header Host $host;
    }
}